# Generated by Django 6.0.6 on 2026-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('leader', 'Leader'), ('citizen', 'Citizen')], default='citizen', max_length=20),
        ),
    ]
