# Generated by Django 6.0.6 on 2026-06-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.dispute')),
            ],
        ),
    ]
