# Generated by Django 6.0.6 on 2026-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='respondent_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent_phone',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
