# Generated by Django 6.0.6 on 2026-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_dispute_respondent_name_dispute_respondent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
