# Generated by Django 6.0.6 on 2026-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0006_dispute_assigned_to_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('village', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='street_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
