# Generated by Django 6.0.6 on 2026-06-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update', models.CharField(choices=[('OPENING', 'Opening'), ('PROGRESS', 'Progress'), ('SCHEDULED', 'Scheduled'), ('SOLVED', 'Solved'), ('ESCALATED', 'Escalated')], max_length=20)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.dispute')),
            ],
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('STAKEHOLDER_REFUSED', 'Stakeholder cannot solve'), ('USER_REJECTED', 'User not satisfied'), ('TIMEOUT', 'No action within time limit')], max_length=50)),
                ('from_level', models.CharField(max_length=50)),
                ('to_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.dispute')),
            ],
        ),
    ]
